// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1PvodTpaM5j3J1TKCRaZ89l9SIQ6nssU',
    appId: '1:865459903803:android:e7405cf66641400785eb1e',
    messagingSenderId: '865459903803',
    projectId: 'izumi-6e087',
    databaseURL: 'https://izumi-6e087-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'izumi-6e087.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdingG8As4kZhzkmsWfA6Xb1mklbDR9-M',
    appId: '1:865459903803:ios:741df537febdb5be85eb1e',
    messagingSenderId: '865459903803',
    projectId: 'izumi-6e087',
    databaseURL: 'https://izumi-6e087-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'izumi-6e087.firebasestorage.app',
    androidClientId: '865459903803-d72jmcthutq1bqd149o7lrgv89fn79o1.apps.googleusercontent.com',
    iosBundleId: 'com.amanrana.izumi',
  );

}